### ISSUE TITLE
当前版本过低，请先升级到手机QQ最新版本。

### ISSUE THREAD

**Issue by liuhulu** [xggz/mqr#2]
2020-12-23 13:45:31 V/Net ********: Send: wtlogin.login
2020-12-23 13:45:32 V/Net ********: Recv: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )
2020-12-23 13:45:32.134 ERROR 12132 --- [    QQ机器人服务运行线程] c.m.mqr.framework.RobotServerStarter     : Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )

net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186) ~[mirai-core-qqandroid-1.3.3.jar:na]
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt) ~[mirai-core-qqandroid-1.3.3.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.4.10.jar:1.4.10-release-411 (1.4.10)]
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32) ~[kotlinx-coroutines-core-jvm-1.4.0.jar:na]
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113) ~[kotlinx-coroutines-core-jvm-1.4.0.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[kotlin-stdlib-1.4.10.jar:1.4.10-release-411 (1.4.10)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.4.0.jar:na]
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274) ~[kotlinx-coroutines-core-jvm-1.4.0.jar:na]
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84) ~[kotlinx-coroutines-core-jvm-1.4.0.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[kotlinx-coroutines-core-jvm-1.4.0.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.4.0.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[kotlinx-coroutines-core-jvm-1.4.0.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.4.0.jar:na]
	at net.mamoe.mirai.BotJavaFriendlyAPI$DefaultImpls.login(BotJavaFriendlyAPI.kt:209) ~[mirai-core-jvm-1.3.3.jar:na]
	at net.mamoe.mirai.Bot.login(Bot.kt:53) ~[mirai-core-jvm-1.3.3.jar:na]
	at com.molicloud.mqr.framework.RobotServerStarter.start(RobotServerStarter.java:92) ~[classes/:na]
	at com.molicloud.mqr.controller.RobotController.lambda$start$0(RobotController.java:58) ~[classes/:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

**Comment by xggz** [comment]
出现这个问题很大概率是因为qq账号或密码不正确，你可以检查看看

**Comment by liuhulu** [comment]
> 出现这个问题很大概率是因为qq账号或密码不正确，你可以检查看看

验证过了，不是密码错误。

**Comment by xggz** [comment]
> > 出现这个问题很大概率是因为qq账号或密码不正确，你可以检查看看
> 
> 验证过了，不是密码错误。

我的几个账号都无法复现此问题

**Comment by liuhulu** [comment]
我又找了一些账号，还是有这个问题。😓

**Comment by liuhulu** [comment]
1.3.3版本中，因为你使用的是测试过的旧账号。新账号是一定会复现的。
https://github.com/mamoe/mirai/issues/621

**Comment by xggz** [comment]
> 1.3.3版本中，因为你使用的是测试过的旧账号。新账号是一定会复现的。
> [mamoe/mirai#621](https://github.com/mamoe/mirai/issues/621)

如果方便的话，可以私聊我账号，我试试

**Comment by xggz** [comment]
> 1.3.3版本中，因为你使用的是测试过的旧账号。新账号是一定会复现的。
> [mamoe/mirai#621](https://github.com/mamoe/mirai/issues/621)

不用私聊我账号了，我也复现出来了

**Comment by barbecue-pan** [comment]
![Uploading image.png…]()
账号密码没有错误

**Comment by xggz** [comment]
> _你的截图暴露了隐私（密码），我给你去掉了_
> 
> 账号密码没有错误

了解，是qq协议的问题，后面我升级一下mirai版本试试

**Comment by xggz** [comment]
已修复协议，Commit：https://github.com/xggz/mqr/commit/f18bc80d9502d1eb58ba6c754eb6d32b3abf33e5
